### PR TITLE
Feature/73 customize automatic form

### LINKED ISSUE #73: Customise automatic form
- [x] There seems to be a problem with buttons at the bottom of data entry. Haven't seen it myself. Let's keep an eye on that
- [x] Grey fields need to be hidden (just for columns)
- [x] Long category option combination makes table too wide
We can find an example of all this in Dataset: DANIDA OLD / OU: NRC

### PR DESCRIPTION
**Pull request by tokland**
Closes #73

(let's comment on the PR before merging)

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland  a few questions before reviewing it:
- Can you please merge latest development into this PR?
- Is this code in dev.est? Otherwise can you please add it?
- Can you double check data entry is displaying fine for you? All fields were displaying greyed for me.

Many thanks!

**Comment by tokland** [comment]
> Can you please merge latest development into this PR?
Done
> Is this code in dev.est? Otherwise can you please add it?
It wasn't, added.
> Can you double check data entry is displaying fine for you? All fields were displaying greyed for me.
Should be unrelated, this happens when the selected period is not in the data input period (so the dataset is considered "locked"). If you select August, it should work. If not, show full webentry selection.

**Comment by adrianq** [comment]
Many thanks @tokland! I will review it asap...

**Comment by adrianq** [comment]
@tokland Grey fields seem to be working fine. Not so sure about long cat combos:
screenshot from 2017-08-15 15-27-42

They are actually split but IMHO there is no need for such a short line. I think in the screenshot attached Host Community and IDP, at least, can go in the same line. Maybe some sort of bug with view port? I have merged this PR so I can keep going reviewing the rest of them. Let me know what you think and let's open a card if we find it to be an issue. Thanks!

**Comment by tokland** [comment]
We saw that in the meeting, but I as too fast: levels are split across whole categories, that was what I thought conceptually made more sense and the fastest. I can refactor to split in the way you expect, on category options trying to join as much as possible.

**Comment by adrianq** [comment]
Sorry, too many things on my mind. I now remember you explaining this bit. Let's keep as it is. I have the impression they will complain about this but let's discuss this at our next meeting. I have created a [card](https://github.com/EyeSeeTea/dataset-configuration/issues/124) so we don't forget. Once again, sorry for not paying enough attention

**Pull request merged**
