### PR TITLE
Optimize requests

### LINKED ISSUE #360: Optimize metadata requests on steps
We already optimised the final POST /metadata request on save, but some intermediate requests made on the wizard step are large:

- [x] Initial Configuration. Large request to /api/categoryOptions -> gets orgUnits[*]. Addressed in #359, check if that's enough.

- [x] Sections. Large initial request to /api/dataElements (work started in branch: optimize-requests-sections-360)

- [ ] Disaggregation & Greyed fields. Large initial request to /api/categoryCombos

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes #360

### :memo: Implementation

- Sections: Use sequential requests for dataElements + categoryCombo + dataElementGroups and join programmatically. This reduces requests significantly when nested items are repeated (as they are in this case).
- Sections: Cache metadata. Currently, there is no expire, so it will be cached until the user reloads the app.
- Disaggregation: Reduce /categoryCombos request
- Grey fields: Reduce /categoryCombos request
- Save Reduce /categoryCombos request
- Dataset edit: reduce /dataSet/ID request.

### CODE REVIEW

**Comment by adrianq** [comment]
I will do some more testing tomorrow. For now, I have only found this minor bug. 
Before:
image

After:
image

**Comment by tokland** [comment]
Good catch, fixed: b6a99ebb

**Comment by adrianq** [comment]
@tokland Another bug, this one when editing a Dataset:
Screenshot from 2019-05-02 13-02-12

You can check it by editing this dataset http://dev.eyeseetea.com:8080/api/apps/dataset-configuration/index.html#/datasets/edit/BoZ17McCtCj?_k=myz9xp or create a new one and edit it afterwards

**Comment by tokland** [comment]
> [edit/BoZ17McCtCj?_k=myz9xp](http://dev.eyeseetea.com:8080/api/apps/dataset-configuration/index.html#/datasets/edit/BoZ17McCtCj?_k=myz9xp)

Not directly related to this PR, but it's a good place to fix. The problem is some dataSetElements ended without categoryCombo (maybe the catCombo was deleted?). For example, check:

http://dev.eyeseetea.com:8080/api/dataSets/BoZ17McCtCj.json?fields=id,name,dataSetElements[dataElement[id,name],categoryCombo]

DataElement `GL-CB702/C-C` has no catCombo.

I've changed all accesses to `dataSetElement.categoryCombo` and now they use a function which returns `dse.dataElement.categoryCombo` as fallback.

**Comment by tokland** [comment]
By the way, while testing of dev:8080, I've detected a but in dhis2 api, not happening in the previous build I was using. See:

http://dev.eyeseetea.com:8080/api/dataElements.json?filter=id:eq:wzo7aYOMj22&fields=id&rootJunction=OR

It returs all dataElements, when only one is being asked in the filter. If you remove `rootJunction=OR` it works as expected, but we need an OR operation. It works on play 2.28.

I'll have to refactor it not not use rootJunction=OR, it's trivial in 2 of the usages, not so trivial on the thirt.

This is important, requests to dataElements and specially categoryCombos (7Mb) are a lot bigger than the one being asked with a filter.

**Pull request merged**
